name: AutoUpdate

on:
  push

jobs:
  update:
    name: Update token list
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: 
          go-version-file: 'go.mod'
      - run: go mod tidy
      - run: go run main.go
