name: Update tokenlist
on:
   push:
     branches:
       - main 
   schedule:
     - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - name: Install dependencies
      run: go mod tidy

    - name: Run 
      run: go run hello.go

    - name: Commit
      run: |
        git config --global user.name "action-user"
        git add .
        git commit -m "Update tokenlist"

    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
